apiVersion: v1
kind: Service
metadata:
  name: service-nodeapp-completion
spec:
  selector:
    app: nodeapp-completion
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000 
